a<-read.csv(file.choose())
View(a)
select(a,id,diagnosis_result)
select(a,-diagnosis_result)
select(a,starts_with("p"))
select(a,ends_with("s"))
select(a,contains("s"))
filter(a,radius>20)
arrange(a,desc(area))
mutate(a,add=perimeter+area)
transmute(a,add=perimeter+area)
rename(a,diagnosresult=diagnosis_result)

select(iris,4)
select(iris,-4)
select(iris,1,2,4)
data()