install.packages("sqldf")
library("sqldf")
a<-read.csv(file.choose())
a
View(sqldf("Select * from a"))
sqldf("Select count(*) from a")
sqldf("Select * from a where marks > 80")
sqldf("Select name,marks from a")
sqldf("Select * from a where name = 'Veer'")
sqldf("Select * from a where marks == 45")
sqldf("Select name from a where marks == 45")
sqldf("Select distinct name from a")
nrow(a)
ncol(a)
nrow(a[a$marks<=33,])
nrow(a[a$marks>33,])
sqldf("Select * from a limit 3")
sqldf("Select * from a order by name desc limit 4")
sqldf("Select * from a where name like 'V%'")
sqldf("Select * from a where name like '%r'")
sqldf("Select * from a where name like '__m%'")
sqldf("Select name as N,marks as M from a")
sqldf("Select sum(marks) from a")
sqldf("Select avg(marks) from a")
sqldf("Select sum(marks) from a where name in ('Vikas','Ankit')")
